/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2021-09-14 10:27:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground: #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.error-container {\r\n");
      out.write("\t\theight: 100vh !important;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\tflex-direction: column;\r\n");
      out.write("\t\tjustify-content: center;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\tfont-family: montserrat, sans-serif;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.big-text {\r\n");
      out.write("\t\tfont-size: 200px;\r\n");
      out.write("\t\tfont-weight: 900;\r\n");
      out.write("\t\tfont-family: sans-serif;\r\n");
      out.write("\t\tbackground: url(https://cdn.pixabay.com/photo/2018/05/30/15/39/thunderstorm-3441687_960_720.jpg) no-repeat;\r\n");
      out.write("\t\t-webkit-background-clip: text;\r\n");
      out.write("\t\t-webkit-text-fill-color: transparent;\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.small-text {\r\n");
      out.write("\t\tfont-family: montserrat, sans-serif;\r\n");
      out.write("\t\tcolor: rgb(0, 0, 0);\r\n");
      out.write("\t\tfont-size: 24px;\r\n");
      out.write("\t\tfont-weight: 700;\r\n");
      out.write("\t\ttext-transform: uppercase;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* Style the search field */\r\n");
      out.write("\t/*form.example input[type=text] {\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\t*/\r\n");
      out.write("\r\n");
      out.write("\t.form-group {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\t/* border: 1px #53a0e4 solid;\r\n");
      out.write("\t\tborder-radius:30px;\r\n");
      out.write("\t\toverflow: hidden;*/\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/*\t\r\n");
      out.write("\t.form-group:focus-within{\r\n");
      out.write("\t   border: 1px green solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t*/\r\n");
      out.write("\r\n");
      out.write("\t/*\tinput:focus + .control-label\r\n");
      out.write("\t*/\r\n");
      out.write("\t.form-control {\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\tbackground: #fff;\r\n");
      out.write("\t\tborder: 1px #53a0e4 solid;\r\n");
      out.write("\t\tborder-right: none;\r\n");
      out.write("\t\tborder-radius: 25px 0px 0px 25px;\r\n");
      out.write("\t\tfont-size: 1rem;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.form-control:focus {\r\n");
      out.write("\t\tborder-color: #61b045;\r\n");
      out.write("\t\tbox-shadow: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* Style the submit button */\r\n");
      out.write("\tform .search-btn {\r\n");
      out.write("\t\tall: unset;\r\n");
      out.write("\t\twidth: 15%;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tbackground: #1e50e2;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tfont-size: 17px;\r\n");
      out.write("\t\tborder: 1px #1e50e2 solid;\r\n");
      out.write("\t\tborder-left: none;\r\n");
      out.write("\t\t/* Prevent double borders */\r\n");
      out.write("\t\tborder: 1px #53a0e4 solid;\r\n");
      out.write("\t\tborder-radius: 0px 25px 25px 0px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tform .search-btn:hover {\r\n");
      out.write("\t\tbackground: #0b7dda;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("\tcolor:\t#fff;\r\n");
      out.write("\tpadding: 12px 36px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-family: 'Raleway', sans-serif;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\t-webkit-border-radius: 90px;\r\n");
      out.write("\t-moz-border-radius: 90px;\r\n");
      out.write("\tborder-radius: 90px;\r\n");
      out.write("\tmargin: 2px;\r\n");
      out.write("\tmargin-top: 2px;\r\n");
      out.write("\tbackground-image: linear-gradient(to right, #09b3ef 0%, #1e50e2 51%,#09b3ef 100%);\r\n");
      out.write("\tbackground-size: 200% auto;\r\n");
      out.write("\tflex: 1 1 auto;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".button:hover,\r\n");
      out.write(".button:focus {\r\n");
      out.write("\tcolor:\t#ffffff;\r\n");
      out.write("\tbackground-position: right center;\r\n");
      out.write("\t-webkit-box-shadow: 0px 5px 15px 0px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\t-moz-box-shadow: 0px 5px 15px 0px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\tbox-shadow: 0px 5px 15px 0px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container error-container\">\r\n");
      out.write("\t<div class=\"row  d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t<h1 class=\"big-text\">Oops!</h1>\r\n");
      out.write("\t\t\t<h2 class=\"small-text\">INAVLID USERNAME OR PASSWORD</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a href=\"index.jsp\"><input type=\"button\" name=\"homepage\" value=\"HOMEPAGE\" class=\"button button-dark-blue iq-mt-15 text-center\"/></a><br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
